services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data

  mqtt-simulator:
    build:
      context: .
    container_name: mqtt-simulator
    environment:
      - SENSORS=5
      - WAIT_TIME=10
    depends_on:
      - mosquitto
    restart: always
